# AUTOGENERATED FROM:
#     'queries/acceptFriendRequest.edgeql'
#     'queries/deleteDraft.edgeql'
#     'queries/deleteFriend.edgeql'
#     'queries/deleteFriendRequest.edgeql'
#     'queries/deleteGlobalUserBoard.edgeql'
#     'queries/deletePixelGraphic.edgeql'
#     'queries/finishDraft.edgeql'
#     'queries/inserUserFromLocalProvider.edgeql'
#     'queries/insertAvatar.edgeql'
#     'queries/insertBoard.edgeql'
#     'queries/insertFriendRequest.edgeql'
#     'queries/insertMessage.edgeql'
#     'queries/insertUserFromGitHubProvider.edgeql'
#     'queries/rejectFriendRequest.edgeql'
#     'queries/searchUserByUsername.edgeql'
#     'queries/selectDraft.edgeql'
#     'queries/selectFriendRequests.edgeql'
#     'queries/selectFriendRequestsSent.edgeql'
#     'queries/selectFriends.edgeql'
#     'queries/selectGlobalIdentity.edgeql'
#     'queries/selectGlobalUser.edgeql'
#     'queries/selectGlobalUserBoard.edgeql'
#     'queries/selectLatestMessage.edgeql'
#     'queries/selectManyGlobalUserBoards.edgeql'
#     'queries/selectUserAvatar.edgeql'
#     'queries/selectUserDrafts.edgeql'
#     'queries/updateGlobalUser.edgeql'
#     'queries/updateGlobalUserBoard.edgeql'
#     'queries/upsertDraft.edgeql'
#     'queries/usernameExists.edgeql'
# WITH:
#     $ gel-py --target blocking --file api/queries.py


from __future__ import annotations
import dataclasses
import datetime
import enum
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


class BoardType(enum.Enum):
    STELLAR = "Stellar"
    GALACTIC = "Galactic"
    COSMIC = "Cosmic"


class BoardType02(enum.Enum):
    STELLAR = "Stellar"
    GALACTIC = "Galactic"
    COSMIC = "Cosmic"


@dataclasses.dataclass
class acceptFriendRequestResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class deleteDraftResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class deleteFriendResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class deleteGlobalUserBoardResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class deletePixelGraphicResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class finishDraftResult(NoPydanticValidation):
    graphic: finishDraftResultGraphic | None
    deleted: deleteDraftResult | None


@dataclasses.dataclass
class finishDraftResultGraphic(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class inserUserFromLocalProviderResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class insertAvatarResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class insertMessageResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class searchUserByUsernameResult(NoPydanticValidation):
    id: uuid.UUID
    username: str | None
    avatar: insertAvatarResult | None


@dataclasses.dataclass
class selectDraftResult(NoPydanticValidation):
    id: uuid.UUID
    binary: bytes
    frames: int
    frame_delay_ms: int
    size: BoardType02
    updated_at: datetime.datetime


@dataclasses.dataclass
class selectFriendRequestsResult(NoPydanticValidation):
    id: uuid.UUID
    sender: searchUserByUsernameResult
    created_at: datetime.datetime


@dataclasses.dataclass
class selectFriendRequestsSentResult(NoPydanticValidation):
    id: uuid.UUID
    recipient: searchUserByUsernameResult
    created_at: datetime.datetime


@dataclasses.dataclass
class selectFriendsResult(NoPydanticValidation):
    id: uuid.UUID
    friend: searchUserByUsernameResult | None
    created_at: datetime.datetime


@dataclasses.dataclass
class selectGlobalIdentityResult(NoPydanticValidation):
    subject: str
    issuer: str
    id: uuid.UUID
    created_at: datetime.datetime
    modified_at: datetime.datetime


@dataclasses.dataclass
class selectGlobalUserBoardResult(NoPydanticValidation):
    id: uuid.UUID
    boardType: BoardType02
    name: str | None
    secret_key_hash: str | None
    secret_updated_at: datetime.datetime | None
    last_connected_at: datetime.datetime | None


@dataclasses.dataclass
class selectGlobalUserResult(NoPydanticValidation):
    username: str | None
    id: uuid.UUID
    email: str | None
    identity: list[selectGlobalUserResultIdentityItem]
    avatar: selectGlobalUserResultAvatar | None


@dataclasses.dataclass
class selectGlobalUserResultAvatar(NoPydanticValidation):
    id: uuid.UUID
    binary: bytes
    created_at: datetime.datetime
    size: BoardType02
    updated_at: datetime.datetime


@dataclasses.dataclass
class selectGlobalUserResultIdentityItem(NoPydanticValidation):
    modified_at: datetime.datetime
    created_at: datetime.datetime
    id: uuid.UUID
    issuer: str
    subject: str


@dataclasses.dataclass
class selectLatestMessageResult(NoPydanticValidation):
    id: uuid.UUID
    graphic: selectLatestMessageResultGraphic
    sender: selectLatestMessageResultSender
    recipient: selectLatestMessageResultSender | None
    sent_at: datetime.datetime | None


@dataclasses.dataclass
class selectLatestMessageResultGraphic(NoPydanticValidation):
    id: uuid.UUID
    binary: bytes
    size: BoardType02


@dataclasses.dataclass
class selectLatestMessageResultSender(NoPydanticValidation):
    id: uuid.UUID
    username: str | None


@dataclasses.dataclass
class selectUserDraftsResult(NoPydanticValidation):
    id: uuid.UUID
    binary: bytes
    frames: int
    frame_delay_ms: int
    size: BoardType02
    created_at: datetime.datetime
    updated_at: datetime.datetime
    active_board: selectUserDraftsResultActiveBoard | None


@dataclasses.dataclass
class selectUserDraftsResultActiveBoard(NoPydanticValidation):
    id: uuid.UUID
    name: str | None


@dataclasses.dataclass
class updateGlobalUserBoardResult(NoPydanticValidation):
    last_connected_at: datetime.datetime | None
    secret_updated_at: datetime.datetime | None
    secret_key_hash: str | None
    name: str | None
    boardType: BoardType02
    id: uuid.UUID


@dataclasses.dataclass
class upsertDraftResult(NoPydanticValidation):
    id: uuid.UUID
    frames: int
    frame_delay_ms: int
    updated_at: datetime.datetime


def acceptFriendRequest(
    executor: gel.Executor,
    *,
    request_id: uuid.UUID,
) -> acceptFriendRequestResult | None:
    return executor.query_single(
        """\
        with
            request := assert_single(
                select FriendRequest
                filter .id = <uuid>$request_id
                    and .recipient.id = global current_user.id
            ),
            sender := request.sender,
            recipient := request.recipient
        insert Friend {
            user1 := sender,
            user2 := recipient
        }
        unless conflict on ((.user1, .user2))
        else (
            select Friend
            filter (.user1 = sender and .user2 = recipient)
                or (.user1 = recipient and .user2 = sender)
        );

        delete FriendRequest
        filter .id = <uuid>$request_id;\
        """,
        request_id=request_id,
    )


def deleteDraft(
    executor: gel.Executor,
    *,
    draft_id: uuid.UUID,
) -> deleteDraftResult | None:
    return executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          )
        delete DraftGraphic
        filter .id = <uuid>$draft_id
          and .creator = user\
        """,
        draft_id=draft_id,
    )


def deleteFriend(
    executor: gel.Executor,
    *,
    friend_id: uuid.UUID,
) -> list[deleteFriendResult]:
    return executor.query(
        """\
        delete Friend
        filter (
            (.user1.id = global current_user.id and .user2.id = <uuid>$friend_id)
            or (.user2.id = global current_user.id and .user1.id = <uuid>$friend_id)
        );\
        """,
        friend_id=friend_id,
    )


def deleteFriendRequest(
    executor: gel.Executor,
    *,
    request_id: uuid.UUID,
) -> acceptFriendRequestResult | None:
    return executor.query_single(
        """\
        delete FriendRequest
        filter .id = <uuid>$request_id
            and .sender.id = global current_user.id;\
        """,
        request_id=request_id,
    )


def deleteGlobalUserBoard(
    executor: gel.Executor,
    *,
    board_id: uuid.UUID,
) -> deleteGlobalUserBoardResult | None:
    return executor.query_single(
        """\
        delete assert_single(
          select Board {*}
          filter .id = <uuid>$board_id and assert_single(
            .owner.identity = global ext::auth::ClientTokenIdentity
          )
        );\
        """,
        board_id=board_id,
    )


def deletePixelGraphic(
    executor: gel.Executor,
    *,
    graphic_id: uuid.UUID,
) -> deletePixelGraphicResult | None:
    return executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          )
        delete PixelGraphic
        filter .id = <uuid>$graphic_id
          and .creator = user\
        """,
        graphic_id=graphic_id,
    )


def finishDraft(
    executor: gel.Executor,
    *,
    draft_id: uuid.UUID,
) -> finishDraftResult:
    return executor.query_single(
        """\
        # Finish a draft by converting it to either StaticImage or PixelAnimation
        # based on whether frames > 1
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          ),
          draft := assert_single(
            select DraftGraphic
            filter .id = <uuid>$draft_id
              and .creator = user
          ),
          # Pre-compute to avoid correlated set issue
          is_animation := draft.frames > 1,
          new_graphic := (
            insert PixelAnimation {
              binary := draft.binary,
              frames := draft.frames,
              frame_delay_ms := draft.frame_delay_ms,
              size := draft.size,
              creator := user
            }
          ) if is_animation else (
            insert StaticImage {
              binary := draft.binary,
              size := draft.size,
              creator := user
            }
          )
        select {
          graphic := new_graphic { id },
          deleted := (delete draft)
        }\
        """,
        draft_id=draft_id,
    )


def inserUserFromLocalProvider(
    executor: gel.Executor,
) -> inserUserFromLocalProviderResult:
    return executor.query_single(
        """\
        with
          identity := (select global ext::auth::ClientTokenIdentity),
          emailFactor := (
            select ext::auth::EmailFactor {email} 
            filter .identity.id = identity.id
          ),
        insert User {
          identity := identity,
          email := emailFactor.email
        }\
        """,
    )


def insertAvatar(
    executor: gel.Executor,
    *,
    data: bytes,
) -> insertAvatarResult:
    return executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          )
        insert Avatar {
          binary := <bytes>$data,
          size := BoardType.Stellar,
          creator := user
        }\
        """,
        data=data,
    )


def insertBoard(
    executor: gel.Executor,
    *,
    board_type: BoardType,
) -> deleteGlobalUserBoardResult:
    return executor.query_single(
        """\
        insert Board {
          boardType := select <BoardType>$board_type,
          owner := select assert_single(
            select User {*}
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          )
        }\
        """,
        board_type=board_type,
    )


def insertFriendRequest(
    executor: gel.Executor,
    *,
    recipient_id: uuid.UUID,
) -> acceptFriendRequestResult | None:
    return executor.query_single(
        """\
        insert FriendRequest {
            sender := global current_user,
            recipient := assert_single(
                select User
                filter .id = <uuid>$recipient_id
            )
        }
        unless conflict on ((.sender, .recipient))
        else (
            select FriendRequest
            filter .sender = global current_user
                and .recipient.id = <uuid>$recipient_id
        );\
        """,
        recipient_id=recipient_id,
    )


def insertMessage(
    executor: gel.Executor,
    *,
    data: bytes,
    size: BoardType,
    recipient_id: uuid.UUID | None = None,
) -> insertMessageResult:
    return executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          ),
          new_graphic := (
            insert StaticImage {
              binary := <bytes>$data,
              size := <BoardType>$size,
              creator := user
            }
          )
        insert Message {
          graphic := new_graphic,
          sender := user,
          recipient := (select User filter .id = <optional uuid>$recipient_id)
        }\
        """,
        data=data,
        size=size,
        recipient_id=recipient_id,
    )


def insertUserFromGitHubProvider(
    executor: gel.Executor,
    *,
    email: str,
) -> inserUserFromLocalProviderResult:
    return executor.query_single(
        """\
        with
          identity := (select global ext::auth::ClientTokenIdentity),
        insert User {
          identity := identity,
          email := <str>$email
        }\
        """,
        email=email,
    )


def rejectFriendRequest(
    executor: gel.Executor,
    *,
    request_id: uuid.UUID,
) -> acceptFriendRequestResult | None:
    return executor.query_single(
        """\
        delete FriendRequest
        filter .id = <uuid>$request_id
            and .recipient.id = global current_user.id;\
        """,
        request_id=request_id,
    )


def searchUserByUsername(
    executor: gel.Executor,
    *,
    username: str,
) -> list[searchUserByUsernameResult]:
    return executor.query(
        """\
        with
            current_user_id := global current_user.id
        select User {
            id,
            username,
            avatar
        }
        filter .username ilike '%' ++ <str>$username ++ '%'
            and .id != current_user_id
            and not exists (
                select Friend
                filter (
                    (.user1.id = current_user_id and .user2.id = .id)
                    or (.user2.id = current_user_id and .user1.id = .id)
                )
            )
            and not exists (
                select FriendRequest
                filter (
                    (.sender.id = current_user_id and .recipient.id = .id)
                    or (.recipient.id = current_user_id and .sender.id = .id)
                )
            )
        order by .username
        limit 10;\
        """,
        username=username,
    )


def selectDraft(
    executor: gel.Executor,
    *,
    board_id: uuid.UUID | None = None,
) -> selectDraftResult | None:
    return executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          )
        select DraftGraphic {
          id,
          binary,
          frames,
          frame_delay_ms,
          size,
          updated_at
        }
        filter .creator = user
          and (
            (.active_board.id = <optional uuid>$board_id) if exists <optional uuid>$board_id
            else not exists .active_board
          )
        limit 1\
        """,
        board_id=board_id,
    )


def selectFriendRequests(
    executor: gel.Executor,
) -> list[selectFriendRequestsResult]:
    return executor.query(
        """\
        select FriendRequest {
            id,
            sender: {
                id,
                username,
                avatar
            },
            created_at
        }
        filter .recipient.id = global current_user.id
        order by .created_at desc;\
        """,
    )


def selectFriendRequestsSent(
    executor: gel.Executor,
) -> list[selectFriendRequestsSentResult]:
    return executor.query(
        """\
        select FriendRequest {
            id,
            recipient: {
                id,
                username,
                avatar
            },
            created_at
        }
        filter .sender.id = global current_user.id
        order by .created_at desc;\
        """,
    )


def selectFriends(
    executor: gel.Executor,
) -> list[selectFriendsResult]:
    return executor.query(
        """\
        with
            current_user_id := global current_user.id,
            friendships := (
                select Friend
                filter .user1.id = current_user_id
                    or .user2.id = current_user_id
            )
        select friendships {
            id,
            friend := (
                select User
                filter .id = (
                    friendships.user1.id if friendships.user2.id = current_user_id
                    else friendships.user2.id
                )
            ) {
                id,
                username,
                avatar
            },
            created_at
        }
        order by .created_at desc;\
        """,
    )


def selectGlobalIdentity(
    executor: gel.Executor,
) -> selectGlobalIdentityResult:
    return executor.query_single(
        """\
        select assert_exists(
          assert_single(
            select global ext::auth::ClientTokenIdentity { * }
          )
        )\
        """,
    )


def selectGlobalUser(
    executor: gel.Executor,
) -> selectGlobalUserResult | None:
    return executor.query_single(
        """\
        select assert_single(
            select User {**}
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
        );\
        """,
    )


def selectGlobalUserBoard(
    executor: gel.Executor,
    *,
    board_id: uuid.UUID,
) -> selectGlobalUserBoardResult | None:
    return executor.query_single(
        """\
        select assert_single(
          select Board {*}
          filter .id = <uuid>$board_id and assert_single(
            .owner.identity = global ext::auth::ClientTokenIdentity
          )
        );\
        """,
        board_id=board_id,
    )


def selectLatestMessage(
    executor: gel.Executor,
) -> selectLatestMessageResult | None:
    return executor.query_single(
        """\
        select Message {
          graphic: { binary, size },
          sender: { id, username },
          recipient: { id, username },
          sent_at
        }
        order by .sent_at desc
        limit 1\
        """,
    )


def selectManyGlobalUserBoards(
    executor: gel.Executor,
) -> list[selectGlobalUserBoardResult]:
    return executor.query(
        """\
        select Board {*}
        filter assert_single(
            .owner.identity = global ext::auth::ClientTokenIdentity
        );\
        """,
    )


def selectUserAvatar(
    executor: gel.Executor,
    *,
    user_id: uuid.UUID,
) -> bytes | None:
    return executor.query_single(
        """\
        select assert_single(
            select User
            filter .id = <uuid>$user_id
        ).avatar.binary;\
        """,
        user_id=user_id,
    )


def selectUserDrafts(
    executor: gel.Executor,
) -> list[selectUserDraftsResult]:
    return executor.query(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          )
        select DraftGraphic {
          id,
          binary,
          frames,
          frame_delay_ms,
          size,
          created_at,
          updated_at,
          active_board: { id, name }
        }
        filter .creator = user
        order by .updated_at desc\
        """,
    )


def updateGlobalUser(
    executor: gel.Executor,
    *,
    avatar_id: uuid.UUID,
    username: str | None = None,
    email: str | None = None,
) -> selectGlobalUserResult | None:
    return executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(
              .identity = global ext::auth::ClientTokenIdentity
            )
          ),
          updated_user := (
            update user
            set {
              avatar := (select Avatar filter .id = <uuid>$avatar_id) if exists(<optional uuid>$avatar_id ?? <optional uuid>{}) else .avatar,
              username := <optional str>$username ?? .username,
              email := <optional str>$email ?? .email
            }
          )
        select updated_user {**};\
        """,
        avatar_id=avatar_id,
        username=username,
        email=email,
    )


def updateGlobalUserBoard(
    executor: gel.Executor,
    *,
    board_id: uuid.UUID,
    board_type: BoardType | None = None,
    name: str | None = None,
    secret_key_hash: str | None = None,
) -> updateGlobalUserBoardResult | None:
    return executor.query_single(
        """\
        with
          board := select assert_single(
            select Board {*}
            filter .id = <uuid>$board_id and assert_single(
              .owner.identity = global ext::auth::ClientTokenIdentity
            )
          ),
          updated_board := (
            update board
            set {
              boardType := <optional BoardType>$board_type ?? .boardType,
              name := <optional str>$name ?? .name,
              secret_key_hash := <optional str>$secret_key_hash ?? .secret_key_hash
            }
          )
        select updated_board{*};\
        """,
        board_id=board_id,
        board_type=board_type,
        name=name,
        secret_key_hash=secret_key_hash,
    )


def upsertDraft(
    executor: gel.Executor,
    *,
    board_id: uuid.UUID | None = None,
    data: bytes,
    frames: int,
    frame_delay_ms: int,
    size: BoardType,
) -> upsertDraftResult | None:
    return executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          ),
          existing := (
            select DraftGraphic
            filter .creator = user
              and (
                (.active_board.id = <optional uuid>$board_id) if exists <optional uuid>$board_id
                else not exists .active_board
              )
            limit 1
          ),
          upserted := (
            update existing
            set {
              binary := <bytes>$data,
              frames := <int16>$frames,
              frame_delay_ms := <int16>$frame_delay_ms,
              size := <BoardType>$size,
              updated_at := datetime_of_statement()
            }
          ) if exists existing else (
            insert DraftGraphic {
              binary := <bytes>$data,
              frames := <int16>$frames,
              frame_delay_ms := <int16>$frame_delay_ms,
              size := <BoardType>$size,
              creator := user,
              active_board := (select Board filter .id = <optional uuid>$board_id)
            }
          )
        select upserted { id, frames, frame_delay_ms, updated_at }\
        """,
        board_id=board_id,
        data=data,
        frames=frames,
        frame_delay_ms=frame_delay_ms,
        size=size,
    )


def usernameExists(
    executor: gel.Executor,
    *,
    username: str,
) -> bool:
    return executor.query_single(
        """\
        select exists (
          select User
          filter .username = <str>$username
        );\
        """,
        username=username,
    )
