# AUTOGENERATED FROM:
#     'queries/inserUserFromLocalProvider.edgeql'
#     'queries/insertBoard.edgeql'
#     'queries/insertUserFromGitHubProvider.edgeql'
#     'queries/selectGlobalIdentity.edgeql'
#     'queries/selectGlobalUser.edgeql'
#     'queries/selectGlobalUserBoard.edgeql'
#     'queries/updateGlobalUserBoard.edgeql'
#     'queries/usernameExists.edgeql'
# WITH:
#     $ gel-py --target blocking --file api/queries.py


from __future__ import annotations
import dataclasses
import datetime
import enum
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


class BoardType(enum.Enum):
    STELLAR = "Stellar"
    GALACTIC = "Galactic"
    COSMIC = "Cosmic"


class BoardType02(enum.Enum):
    STELLAR = "Stellar"
    GALACTIC = "Galactic"
    COSMIC = "Cosmic"


@dataclasses.dataclass
class inserUserFromLocalProviderResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class insertBoardResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class selectGlobalIdentityResult(NoPydanticValidation):
    subject: str
    issuer: str
    id: uuid.UUID
    created_at: datetime.datetime
    modified_at: datetime.datetime


@dataclasses.dataclass
class selectGlobalUserBoardResult(NoPydanticValidation):
    id: uuid.UUID
    boardType: BoardType02
    name: str | None
    secret_key_hash: str | None
    secret_updated_at: datetime.datetime | None
    last_connected_at: datetime.datetime | None


@dataclasses.dataclass
class selectGlobalUserResult(NoPydanticValidation):
    username: str | None
    id: uuid.UUID
    email: str | None


@dataclasses.dataclass
class updateGlobalUserBoardResult(NoPydanticValidation):
    last_connected_at: datetime.datetime | None
    secret_updated_at: datetime.datetime | None
    secret_key_hash: str | None
    name: str | None
    boardType: BoardType02
    id: uuid.UUID


def inserUserFromLocalProvider(
    executor: gel.Executor,
) -> inserUserFromLocalProviderResult:
    return executor.query_single(
        """\
        with
          identity := (select global ext::auth::ClientTokenIdentity),
          emailFactor := (
            select ext::auth::EmailFactor {email} 
            filter .identity.id = identity.id
          ),
        insert User {
          identity := identity,
          email := emailFactor.email
        }\
        """,
    )


def insertBoard(
    executor: gel.Executor,
    *,
    board_type: BoardType,
) -> insertBoardResult:
    return executor.query_single(
        """\
        insert Board {
          boardType := select <BoardType>$board_type,
          owner := select assert_single(
            select User {*}
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          )
        }\
        """,
        board_type=board_type,
    )


def insertUserFromGitHubProvider(
    executor: gel.Executor,
    *,
    email: str,
) -> inserUserFromLocalProviderResult:
    return executor.query_single(
        """\
        with
          identity := (select global ext::auth::ClientTokenIdentity),
        insert User {
          identity := identity,
          email := <str>$email
        }\
        """,
        email=email,
    )


def selectGlobalIdentity(
    executor: gel.Executor,
) -> selectGlobalIdentityResult:
    return executor.query_single(
        """\
        select assert_exists(
          assert_single(
            select global ext::auth::ClientTokenIdentity { * }
          )
        )\
        """,
    )


def selectGlobalUser(
    executor: gel.Executor,
) -> selectGlobalUserResult | None:
    return executor.query_single(
        """\
        select assert_single(
            select User {*}
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
        );\
        """,
    )


def selectGlobalUserBoard(
    executor: gel.Executor,
    *,
    board_id: uuid.UUID,
) -> selectGlobalUserBoardResult | None:
    return executor.query_single(
        """\
        select assert_single(
          select Board {*}
          filter .id = <uuid>$board_id and assert_single(
            .owner.identity = global ext::auth::ClientTokenIdentity
          )
        );\
        """,
        board_id=board_id,
    )


def updateGlobalUserBoard(
    executor: gel.Executor,
    *,
    board_id: uuid.UUID,
    board_type: BoardType | None = None,
    name: str | None = None,
    secret_key_hash: str | None = None,
) -> updateGlobalUserBoardResult | None:
    return executor.query_single(
        """\
        with
          board := select assert_single(
            select Board {*}
            filter .id = <uuid>$board_id and assert_single(
              .owner.identity = global ext::auth::ClientTokenIdentity
            )
          ),
          updated_board := (
            update board
            set {
              boardType := <optional BoardType>$board_type ?? .boardType,
              name := <optional str>$name ?? .name,
              secret_key_hash := <optional str>$secret_key_hash ?? .secret_key_hash
            }
          )
        select updated_board{*};\
        """,
        board_id=board_id,
        board_type=board_type,
        name=name,
        secret_key_hash=secret_key_hash,
    )


def usernameExists(
    executor: gel.Executor,
    *,
    username: str,
) -> bool:
    return executor.query_single(
        """\
        select exists (
          select User
          filter .username = <str>$username
        );\
        """,
        username=username,
    )
