# AUTOGENERATED FROM:
#     'queries/acceptFriendRequest.edgeql'
#     'queries/copyGraphicToDraft.edgeql'
#     'queries/copyGraphicToGallery.edgeql'
#     'queries/deleteDraft.edgeql'
#     'queries/deleteFriend.edgeql'
#     'queries/deleteFriendRequest.edgeql'
#     'queries/deleteGlobalUserBoard.edgeql'
#     'queries/deletePixelGraphic.edgeql'
#     'queries/deleteRecipientMessage.edgeql'
#     'queries/finishDraft.edgeql'
#     'queries/inserUserFromLocalProvider.edgeql'
#     'queries/insertAvatar.edgeql'
#     'queries/insertBoard.edgeql'
#     'queries/insertFriendRequest.edgeql'
#     'queries/insertMessage.edgeql'
#     'queries/insertMessageWithBoard.edgeql'
#     'queries/insertUserFromGitHubProvider.edgeql'
#     'queries/markMessageRead.edgeql'
#     'queries/rejectFriendRequest.edgeql'
#     'queries/searchUserByUsername.edgeql'
#     'queries/selectBoardBySecretKey.edgeql'
#     'queries/selectDraft.edgeql'
#     'queries/selectFriendRequests.edgeql'
#     'queries/selectFriendRequestsSent.edgeql'
#     'queries/selectFriends.edgeql'
#     'queries/selectGlobalIdentity.edgeql'
#     'queries/selectGlobalUser.edgeql'
#     'queries/selectGlobalUserBoard.edgeql'
#     'queries/selectLatestMessage.edgeql'
#     'queries/selectManyGlobalUserBoards.edgeql'
#     'queries/selectMessageForSpacePack.edgeql'
#     'queries/selectPixelGraphic.edgeql'
#     'queries/selectUserAvatar.edgeql'
#     'queries/selectUserDrafts.edgeql'
#     'queries/selectUserGraphics.edgeql'
#     'queries/selectUserMessages.edgeql'
#     'queries/selectUserMessagesRecent.edgeql'
#     'queries/updateGlobalUser.edgeql'
#     'queries/updateGlobalUserBoard.edgeql'
#     'queries/upsertDraft.edgeql'
#     'queries/usernameExists.edgeql'
# WITH:
#     $ gel-py --target async --file api/queries.py


from __future__ import annotations
import dataclasses
import datetime
import enum
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


class BoardType(enum.Enum):
    STELLAR = "Stellar"
    GALACTIC = "Galactic"
    COSMIC = "Cosmic"


class BoardType02(enum.Enum):
    STELLAR = "Stellar"
    GALACTIC = "Galactic"
    COSMIC = "Cosmic"


@dataclasses.dataclass
class acceptFriendRequestResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class copyGraphicToDraftResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class copyGraphicToGalleryResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class deleteFriendResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class deleteGlobalUserBoardResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class deletePixelGraphicResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class deleteRecipientMessageResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class finishDraftResult(NoPydanticValidation):
    graphic: copyGraphicToGalleryResult | None
    deleted: copyGraphicToDraftResult | None


@dataclasses.dataclass
class inserUserFromLocalProviderResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class insertAvatarResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class searchUserByUsernameResult(NoPydanticValidation):
    id: uuid.UUID
    username: str | None
    avatar: insertAvatarResult | None


@dataclasses.dataclass
class selectBoardBySecretKeyResult(NoPydanticValidation):
    id: uuid.UUID
    boardType: BoardType02
    name: str | None
    secret_key_hash: str | None
    owner_id: uuid.UUID


@dataclasses.dataclass
class selectDraftResult(NoPydanticValidation):
    id: uuid.UUID
    binary: bytes
    frames: int
    fps: int
    size: BoardType02
    updated_at: datetime.datetime


@dataclasses.dataclass
class selectFriendRequestsResult(NoPydanticValidation):
    id: uuid.UUID
    sender: searchUserByUsernameResult
    created_at: datetime.datetime


@dataclasses.dataclass
class selectFriendRequestsSentResult(NoPydanticValidation):
    id: uuid.UUID
    recipient: searchUserByUsernameResult
    created_at: datetime.datetime


@dataclasses.dataclass
class selectFriendsResult(NoPydanticValidation):
    id: uuid.UUID
    friend: searchUserByUsernameResult | None
    created_at: datetime.datetime


@dataclasses.dataclass
class selectGlobalIdentityResult(NoPydanticValidation):
    subject: str
    issuer: str
    id: uuid.UUID
    created_at: datetime.datetime
    modified_at: datetime.datetime


@dataclasses.dataclass
class selectGlobalUserBoardResult(NoPydanticValidation):
    id: uuid.UUID
    boardType: BoardType02
    name: str | None
    secret_key_hash: str | None
    secret_updated_at: datetime.datetime | None
    last_connected_at: datetime.datetime | None


@dataclasses.dataclass
class selectGlobalUserResult(NoPydanticValidation):
    username: str | None
    id: uuid.UUID
    email: str | None
    identity: list[selectGlobalUserResultIdentityItem]
    avatar: selectGlobalUserResultAvatar | None


@dataclasses.dataclass
class selectGlobalUserResultAvatar(NoPydanticValidation):
    id: uuid.UUID
    binary: bytes
    created_at: datetime.datetime
    size: BoardType02
    updated_at: datetime.datetime


@dataclasses.dataclass
class selectGlobalUserResultIdentityItem(NoPydanticValidation):
    modified_at: datetime.datetime
    created_at: datetime.datetime
    id: uuid.UUID
    issuer: str
    subject: str


@dataclasses.dataclass
class selectLatestMessageResult(NoPydanticValidation):
    id: uuid.UUID
    graphic: selectLatestMessageResultGraphic
    sender: selectLatestMessageResultSender
    recipient: selectLatestMessageResultSender | None
    sent_at: datetime.datetime | None


@dataclasses.dataclass
class selectLatestMessageResultGraphic(NoPydanticValidation):
    id: uuid.UUID
    binary: bytes
    size: BoardType02


@dataclasses.dataclass
class selectLatestMessageResultSender(NoPydanticValidation):
    id: uuid.UUID
    username: str | None


@dataclasses.dataclass
class selectMessageForSpacePackResult(NoPydanticValidation):
    id: uuid.UUID
    graphic_binary: bytes
    graphic_size: BoardType02
    graphic_frames: int
    graphic_fps: int
    sender_username: str | None
    sender_id: uuid.UUID


@dataclasses.dataclass
class selectPixelGraphicResult(NoPydanticValidation):
    id: uuid.UUID
    binary: bytes
    size: BoardType02
    created_at: datetime.datetime
    updated_at: datetime.datetime


@dataclasses.dataclass
class selectUserDraftsResult(NoPydanticValidation):
    id: uuid.UUID
    binary: bytes
    frames: int
    fps: int
    size: BoardType02
    created_at: datetime.datetime
    updated_at: datetime.datetime
    active_board: selectUserDraftsResultActiveBoard | None


@dataclasses.dataclass
class selectUserDraftsResultActiveBoard(NoPydanticValidation):
    id: uuid.UUID
    name: str | None


@dataclasses.dataclass
class selectUserGraphicsResult(NoPydanticValidation):
    id: uuid.UUID
    binary: bytes
    size: BoardType02
    created_at: datetime.datetime
    updated_at: datetime.datetime
    frames: int
    fps: int


@dataclasses.dataclass
class selectUserMessagesRecentResult(NoPydanticValidation):
    id: uuid.UUID
    sent_at: datetime.datetime | None
    sender: selectLatestMessageResultSender
    recipient: selectLatestMessageResultSender | None
    graphic: selectUserMessagesResultGraphic


@dataclasses.dataclass
class selectUserMessagesResult(NoPydanticValidation):
    id: uuid.UUID
    sent_at: datetime.datetime | None
    is_read: bool | None
    sender: selectLatestMessageResultSender
    recipient: selectLatestMessageResultSender | None
    graphic: selectUserMessagesResultGraphic


@dataclasses.dataclass
class selectUserMessagesResultGraphic(NoPydanticValidation):
    id: uuid.UUID
    size: BoardType02
    frames: int
    fps: int


@dataclasses.dataclass
class updateGlobalUserBoardResult(NoPydanticValidation):
    last_connected_at: datetime.datetime | None
    secret_updated_at: datetime.datetime | None
    secret_key_hash: str | None
    name: str | None
    boardType: BoardType02
    id: uuid.UUID


@dataclasses.dataclass
class upsertDraftResult(NoPydanticValidation):
    id: uuid.UUID
    frames: int
    fps: int
    updated_at: datetime.datetime


async def acceptFriendRequest(
    executor: gel.AsyncIOExecutor,
    *,
    request_id: uuid.UUID,
) -> acceptFriendRequestResult | None:
    return await executor.query_single(
        """\
        with
            request := assert_single(
                select FriendRequest
                filter .id = <uuid>$request_id
                    and .recipient.id = global current_user.id
            ),
            sender := request.sender,
            recipient := request.recipient
        insert Friend {
            user1 := sender,
            user2 := recipient
        }
        unless conflict on ((.user1, .user2))
        else (
            select Friend
            filter (.user1 = sender and .user2 = recipient)
                or (.user1 = recipient and .user2 = sender)
        );

        delete FriendRequest
        filter .id = <uuid>$request_id;\
        """,
        request_id=request_id,
    )


async def copyGraphicToDraft(
    executor: gel.AsyncIOExecutor,
    *,
    graphic_id: uuid.UUID,
) -> copyGraphicToDraftResult:
    return await executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          ),
          source := assert_single(
            select PixelGraphic
            filter .id = <uuid>$graphic_id
          )
        insert DraftGraphic {
          creator := user,
          binary := source.binary,
          size := source.size,
          frames := source[is PixelAnimation].frames ?? 1,
          fps := source[is PixelAnimation].fps ?? 10
        }\
        """,
        graphic_id=graphic_id,
    )


async def copyGraphicToGallery(
    executor: gel.AsyncIOExecutor,
    *,
    graphic_id: uuid.UUID,
) -> copyGraphicToGalleryResult | None:
    return await executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter global ext::auth::ClientTokenIdentity in .identity
          ),
          source := assert_single(
            select PixelGraphic
            filter .id = <uuid>$graphic_id
          ),
          is_animation := source is PixelAnimation,
          new_graphic := (
            insert PixelAnimation {
              binary := source.binary,
              frames := source[is PixelAnimation].frames ?? <int16>1,
              fps := source[is PixelAnimation].fps ?? <int16>10,
              size := source.size,
              creator := user
            }
          ) if is_animation else (
            insert StaticImage {
              binary := source.binary,
              size := source.size,
              creator := user
            }
          )
        select new_graphic { id }\
        """,
        graphic_id=graphic_id,
    )


async def deleteDraft(
    executor: gel.AsyncIOExecutor,
    *,
    draft_id: uuid.UUID,
) -> copyGraphicToDraftResult | None:
    return await executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          )
        delete DraftGraphic
        filter .id = <uuid>$draft_id
          and .creator = user\
        """,
        draft_id=draft_id,
    )


async def deleteFriend(
    executor: gel.AsyncIOExecutor,
    *,
    friend_id: uuid.UUID,
) -> list[deleteFriendResult]:
    return await executor.query(
        """\
        delete Friend
        filter (
            (.user1.id = global current_user.id and .user2.id = <uuid>$friend_id)
            or (.user2.id = global current_user.id and .user1.id = <uuid>$friend_id)
        );\
        """,
        friend_id=friend_id,
    )


async def deleteFriendRequest(
    executor: gel.AsyncIOExecutor,
    *,
    request_id: uuid.UUID,
) -> acceptFriendRequestResult | None:
    return await executor.query_single(
        """\
        delete FriendRequest
        filter .id = <uuid>$request_id
            and .sender.id = global current_user.id;\
        """,
        request_id=request_id,
    )


async def deleteGlobalUserBoard(
    executor: gel.AsyncIOExecutor,
    *,
    board_id: uuid.UUID,
) -> deleteGlobalUserBoardResult | None:
    return await executor.query_single(
        """\
        delete assert_single(
          select Board {*}
          filter .id = <uuid>$board_id and assert_single(
            .owner.identity = global ext::auth::ClientTokenIdentity
          )
        );\
        """,
        board_id=board_id,
    )


async def deletePixelGraphic(
    executor: gel.AsyncIOExecutor,
    *,
    graphic_id: uuid.UUID,
) -> deletePixelGraphicResult | None:
    return await executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          )
        delete PixelGraphic
        filter .id = <uuid>$graphic_id
          and .creator = user\
        """,
        graphic_id=graphic_id,
    )


async def deleteRecipientMessage(
    executor: gel.AsyncIOExecutor,
    *,
    message_id: uuid.UUID,
) -> deleteRecipientMessageResult | None:
    return await executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter global ext::auth::ClientTokenIdentity in .identity
          )
        delete Message
        filter .id = <uuid>$message_id
          and .recipient = user\
        """,
        message_id=message_id,
    )


async def finishDraft(
    executor: gel.AsyncIOExecutor,
    *,
    draft_id: uuid.UUID,
) -> finishDraftResult:
    return await executor.query_single(
        """\
        # Finish a draft by converting it to either StaticImage or PixelAnimation
        # based on whether frames > 1
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          ),
          draft := assert_single(
            select DraftGraphic
            filter .id = <uuid>$draft_id
              and .creator = user
          ),
          # Pre-compute to avoid correlated set issue
          is_animation := draft.frames > 1,
          new_graphic := (
            insert PixelAnimation {
              binary := draft.binary,
              frames := draft.frames,
              fps := draft.fps,
              size := draft.size,
              creator := user
            }
          ) if is_animation else (
            insert StaticImage {
              binary := draft.binary,
              size := draft.size,
              creator := user
            }
          )
        select {
          graphic := new_graphic { id },
          deleted := (delete draft)
        }\
        """,
        draft_id=draft_id,
    )


async def inserUserFromLocalProvider(
    executor: gel.AsyncIOExecutor,
) -> inserUserFromLocalProviderResult:
    return await executor.query_single(
        """\
        with
          identity := (select global ext::auth::ClientTokenIdentity),
          emailFactor := (
            select ext::auth::EmailFactor {email} 
            filter .identity.id = identity.id
          ),
        insert User {
          identity := identity,
          email := emailFactor.email
        }\
        """,
    )


async def insertAvatar(
    executor: gel.AsyncIOExecutor,
    *,
    data: bytes,
) -> insertAvatarResult:
    return await executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          )
        insert Avatar {
          binary := <bytes>$data,
          size := BoardType.Stellar,
          creator := user
        }\
        """,
        data=data,
    )


async def insertBoard(
    executor: gel.AsyncIOExecutor,
    *,
    board_type: BoardType,
) -> deleteGlobalUserBoardResult:
    return await executor.query_single(
        """\
        insert Board {
          boardType := select <BoardType>$board_type,
          owner := select assert_single(
            select User {*}
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          )
        }\
        """,
        board_type=board_type,
    )


async def insertFriendRequest(
    executor: gel.AsyncIOExecutor,
    *,
    recipient_id: uuid.UUID,
) -> acceptFriendRequestResult | None:
    return await executor.query_single(
        """\
        insert FriendRequest {
            sender := global current_user,
            recipient := assert_single(
                select User
                filter .id = <uuid>$recipient_id
            )
        }
        unless conflict on ((.sender, .recipient))
        else (
            select FriendRequest
            filter .sender = global current_user
                and .recipient.id = <uuid>$recipient_id
        );\
        """,
        recipient_id=recipient_id,
    )


async def insertMessage(
    executor: gel.AsyncIOExecutor,
    *,
    data: bytes,
    size: BoardType,
    recipient_id: uuid.UUID | None = None,
) -> deleteRecipientMessageResult:
    return await executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          ),
          new_graphic := (
            insert StaticImage {
              binary := <bytes>$data,
              size := <BoardType>$size,
              creator := user
            }
          )
        insert Message {
          graphic := new_graphic,
          sender := user,
          recipient := (select User filter .id = <optional uuid>$recipient_id)
        }\
        """,
        data=data,
        size=size,
        recipient_id=recipient_id,
    )


async def insertMessageWithBoard(
    executor: gel.AsyncIOExecutor,
    *,
    graphic_id: uuid.UUID,
    recipient_id: uuid.UUID | None = None,
) -> deleteRecipientMessageResult:
    return await executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter global ext::auth::ClientTokenIdentity in .identity
          ),
          graphic := assert_single(
            select PixelGraphic
            filter .id = <uuid>$graphic_id
          )
        insert Message {
          graphic := graphic,
          sender := user,
          recipient := (select User filter .id = <optional uuid>$recipient_id)
        }\
        """,
        graphic_id=graphic_id,
        recipient_id=recipient_id,
    )


async def insertUserFromGitHubProvider(
    executor: gel.AsyncIOExecutor,
    *,
    email: str,
) -> inserUserFromLocalProviderResult:
    return await executor.query_single(
        """\
        with
          identity := (select global ext::auth::ClientTokenIdentity),
        insert User {
          identity := identity,
          email := <str>$email
        }\
        """,
        email=email,
    )


async def markMessageRead(
    executor: gel.AsyncIOExecutor,
    *,
    message_id: uuid.UUID,
) -> deleteRecipientMessageResult | None:
    return await executor.query_single(
        """\
        update Message
        filter .id = <uuid>$message_id
        set { is_read := true }\
        """,
        message_id=message_id,
    )


async def rejectFriendRequest(
    executor: gel.AsyncIOExecutor,
    *,
    request_id: uuid.UUID,
) -> acceptFriendRequestResult | None:
    return await executor.query_single(
        """\
        delete FriendRequest
        filter .id = <uuid>$request_id
            and .recipient.id = global current_user.id;\
        """,
        request_id=request_id,
    )


async def searchUserByUsername(
    executor: gel.AsyncIOExecutor,
    *,
    username: str,
) -> list[searchUserByUsernameResult]:
    return await executor.query(
        """\
        with
            current_user_id := global current_user.id
        select User {
            id,
            username,
            avatar
        }
        filter .username ilike '%' ++ <str>$username ++ '%'
            and .id != current_user_id
            and not exists (
                select Friend
                filter (
                    (.user1.id = current_user_id and .user2.id = .id)
                    or (.user2.id = current_user_id and .user1.id = .id)
                )
            )
            and not exists (
                select FriendRequest
                filter (
                    (.sender.id = current_user_id and .recipient.id = .id)
                    or (.recipient.id = current_user_id and .sender.id = .id)
                )
            )
        order by .username
        limit 10;\
        """,
        username=username,
    )


async def selectBoardBySecretKey(
    executor: gel.AsyncIOExecutor,
    *,
    board_id: uuid.UUID,
) -> selectBoardBySecretKeyResult | None:
    return await executor.query_single(
        """\
        select Board {
          id,
          boardType,
          name,
          secret_key_hash,
          owner_id := .owner.id
        }
        filter .id = <uuid>$board_id
        limit 1\
        """,
        board_id=board_id,
    )


async def selectDraft(
    executor: gel.AsyncIOExecutor,
    *,
    draft_id: uuid.UUID | None = None,
    board_id: uuid.UUID | None = None,
) -> selectDraftResult | None:
    return await executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          )
        select DraftGraphic {
          id,
          binary,
          frames,
          fps,
          size,
          updated_at
        }
        filter .creator = user
          and (
            (.id = <optional uuid>$draft_id) if exists <optional uuid>$draft_id else
            (
              (.active_board.id = <optional uuid>$board_id) if exists <optional uuid>$board_id
              else not exists .active_board
            )
          )
        limit 1\
        """,
        draft_id=draft_id,
        board_id=board_id,
    )


async def selectFriendRequests(
    executor: gel.AsyncIOExecutor,
) -> list[selectFriendRequestsResult]:
    return await executor.query(
        """\
        select FriendRequest {
            id,
            sender: {
                id,
                username,
                avatar
            },
            created_at
        }
        filter .recipient.id = global current_user.id
        order by .created_at desc;\
        """,
    )


async def selectFriendRequestsSent(
    executor: gel.AsyncIOExecutor,
) -> list[selectFriendRequestsSentResult]:
    return await executor.query(
        """\
        select FriendRequest {
            id,
            recipient: {
                id,
                username,
                avatar
            },
            created_at
        }
        filter .sender.id = global current_user.id
        order by .created_at desc;\
        """,
    )


async def selectFriends(
    executor: gel.AsyncIOExecutor,
) -> list[selectFriendsResult]:
    return await executor.query(
        """\
        with
            current_user_id := global current_user.id,
            friendships := (
                select Friend
                filter .user1.id = current_user_id
                    or .user2.id = current_user_id
            )
        select friendships {
            id,
            friend := (
                select User
                filter .id = (
                    friendships.user1.id if friendships.user2.id = current_user_id
                    else friendships.user2.id
                )
            ) {
                id,
                username,
                avatar
            },
            created_at
        }
        order by .created_at desc;\
        """,
    )


async def selectGlobalIdentity(
    executor: gel.AsyncIOExecutor,
) -> selectGlobalIdentityResult:
    return await executor.query_single(
        """\
        select assert_exists(
          assert_single(
            select global ext::auth::ClientTokenIdentity { * }
          )
        )\
        """,
    )


async def selectGlobalUser(
    executor: gel.AsyncIOExecutor,
) -> selectGlobalUserResult | None:
    return await executor.query_single(
        """\
        select assert_single(
            select User {**}
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
        );\
        """,
    )


async def selectGlobalUserBoard(
    executor: gel.AsyncIOExecutor,
    *,
    board_id: uuid.UUID,
) -> selectGlobalUserBoardResult | None:
    return await executor.query_single(
        """\
        select assert_single(
          select Board {*}
          filter .id = <uuid>$board_id and assert_single(
            .owner.identity = global ext::auth::ClientTokenIdentity
          )
        );\
        """,
        board_id=board_id,
    )


async def selectLatestMessage(
    executor: gel.AsyncIOExecutor,
) -> selectLatestMessageResult | None:
    return await executor.query_single(
        """\
        select Message {
          graphic: { binary, size },
          sender: { id, username },
          recipient: { id, username },
          sent_at
        }
        order by .sent_at desc
        limit 1\
        """,
    )


async def selectManyGlobalUserBoards(
    executor: gel.AsyncIOExecutor,
) -> list[selectGlobalUserBoardResult]:
    return await executor.query(
        """\
        select Board {*}
        filter assert_single(
            .owner.identity = global ext::auth::ClientTokenIdentity
        );\
        """,
    )


async def selectMessageForSpacePack(
    executor: gel.AsyncIOExecutor,
    *,
    message_id: uuid.UUID,
) -> selectMessageForSpacePackResult | None:
    return await executor.query_single(
        """\
        select Message {
          id,
          graphic_binary := .graphic.binary,
          graphic_size := .graphic.size,
          graphic_frames := .graphic[is PixelAnimation].frames ?? <int16>1,
          graphic_fps := .graphic[is PixelAnimation].fps ?? <int16>10,
          sender_username := .sender.username,
          sender_id := .sender.id
        }
        filter .id = <uuid>$message_id
        limit 1\
        """,
        message_id=message_id,
    )


async def selectPixelGraphic(
    executor: gel.AsyncIOExecutor,
    *,
    graphic_id: uuid.UUID,
) -> selectPixelGraphicResult | None:
    return await executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          )
        select PixelGraphic {
          id,
          binary,
          size,
          created_at,
          updated_at
        }
        filter .id = <uuid>$graphic_id
          # Allow viewing if creator OR recipient of a message containing it?
          # For now just creator or global lookup (since messages are shared)
          # But technically PixelGraphic has a required creator.
          # Let's just filter by ID for serving images, maybe with basic auth check if needed.
          # But for now, let's keep it simple.
          limit 1\
        """,
        graphic_id=graphic_id,
    )


async def selectUserAvatar(
    executor: gel.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> bytes | None:
    return await executor.query_single(
        """\
        select assert_single(
            select User
            filter .id = <uuid>$user_id
        ).avatar.binary;\
        """,
        user_id=user_id,
    )


async def selectUserDrafts(
    executor: gel.AsyncIOExecutor,
) -> list[selectUserDraftsResult]:
    return await executor.query(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          )
        select DraftGraphic {
          id,
          binary,
          frames,
          fps,
          size,
          created_at,
          updated_at,
          active_board: { id, name }
        }
        filter .creator = user
        order by .updated_at desc\
        """,
    )


async def selectUserGraphics(
    executor: gel.AsyncIOExecutor,
) -> list[selectUserGraphicsResult]:
    return await executor.query(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          )
        select g := PixelGraphic {
          id,
          binary,
          size,
          created_at,
          updated_at,
          frames := [is PixelAnimation].frames ?? <int16>1,
          fps := [is PixelAnimation].fps ?? <int16>10
        }
        filter g.creator = user
          and not (g is DraftGraphic)
          and not (g is Avatar)
          and not exists (select Message filter .graphic = g)
        order by g.updated_at desc\
        """,
    )


async def selectUserMessages(
    executor: gel.AsyncIOExecutor,
    *,
    offset: int,
    limit: int,
) -> list[selectUserMessagesResult]:
    return await executor.query(
        """\
        with
          user := assert_single(
            select User
            filter global ext::auth::ClientTokenIdentity in .identity
          )
        select Message {
          id,
          sent_at,
          is_read,
          sender: { id, username },
          recipient: { id, username },
          graphic: {
            id,
            size,
            frames := [is PixelAnimation].frames ?? <int16>1,
            fps := [is PixelAnimation].fps ?? <int16>10
          }
        }
        filter .recipient = user
        order by .sent_at desc
        offset <int64>$offset
        limit <int64>$limit\
        """,
        offset=offset,
        limit=limit,
    )


async def selectUserMessagesRecent(
    executor: gel.AsyncIOExecutor,
) -> list[selectUserMessagesRecentResult]:
    return await executor.query(
        """\
        with
          user := assert_single(
            select User
            filter global ext::auth::ClientTokenIdentity in .identity
          )
        select Message {
          id,
          sent_at,
          sender: { id, username },
          recipient: { id, username },
          graphic: {
            id,
            size,
            frames := [is PixelAnimation].frames ?? <int16>1,
            fps := [is PixelAnimation].fps ?? <int16>10
          }
        }
        filter .recipient = user
        order by .sent_at desc
        limit 5\
        """,
    )


async def updateGlobalUser(
    executor: gel.AsyncIOExecutor,
    *,
    avatar_id: uuid.UUID,
    username: str | None = None,
    email: str | None = None,
) -> selectGlobalUserResult | None:
    return await executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(
              .identity = global ext::auth::ClientTokenIdentity
            )
          ),
          updated_user := (
            update user
            set {
              avatar := (select Avatar filter .id = <uuid>$avatar_id) if exists(<optional uuid>$avatar_id ?? <optional uuid>{}) else .avatar,
              username := <optional str>$username ?? .username,
              email := <optional str>$email ?? .email
            }
          )
        select updated_user {**};\
        """,
        avatar_id=avatar_id,
        username=username,
        email=email,
    )


async def updateGlobalUserBoard(
    executor: gel.AsyncIOExecutor,
    *,
    board_id: uuid.UUID,
    board_type: BoardType | None = None,
    name: str | None = None,
    secret_key_hash: str | None = None,
) -> updateGlobalUserBoardResult | None:
    return await executor.query_single(
        """\
        with
          board := select assert_single(
            select Board {*}
            filter .id = <uuid>$board_id and assert_single(
              .owner.identity = global ext::auth::ClientTokenIdentity
            )
          ),
          updated_board := (
            update board
            set {
              boardType := <optional BoardType>$board_type ?? .boardType,
              name := <optional str>$name ?? .name,
              secret_key_hash := <optional str>$secret_key_hash ?? .secret_key_hash
            }
          )
        select updated_board{*};\
        """,
        board_id=board_id,
        board_type=board_type,
        name=name,
        secret_key_hash=secret_key_hash,
    )


async def upsertDraft(
    executor: gel.AsyncIOExecutor,
    *,
    draft_id: uuid.UUID | None = None,
    data: bytes,
    frames: int,
    fps: int,
    size: BoardType,
    board_id: uuid.UUID | None = None,
) -> upsertDraftResult | None:
    return await executor.query_single(
        """\
        with
          user := assert_single(
            select User
            filter assert_single(.identity = global ext::auth::ClientTokenIdentity)
          ),
          existing := (
            select DraftGraphic
            filter .id = <optional uuid>$draft_id
              and .creator = user
          ),
          upserted := (
            update existing
            set {
              binary := <bytes>$data,
              frames := <int16>$frames,
              fps := <int16>$fps,
              size := <BoardType>$size,
              active_board := (select Board filter .id = <optional uuid>$board_id),
              updated_at := datetime_of_statement()
            }
          ) if exists existing else (
            insert DraftGraphic {
              binary := <bytes>$data,
              frames := <int16>$frames,
              fps := <int16>$fps,
              size := <BoardType>$size,
              creator := user,
              active_board := (select Board filter .id = <optional uuid>$board_id)
            }
          )
        select upserted { id, frames, fps, updated_at }\
        """,
        draft_id=draft_id,
        data=data,
        frames=frames,
        fps=fps,
        size=size,
        board_id=board_id,
    )


async def usernameExists(
    executor: gel.AsyncIOExecutor,
    *,
    username: str,
) -> bool:
    return await executor.query_single(
        """\
        select exists (
          select User
          filter .username = <str>$username
        );\
        """,
        username=username,
    )
